server:
  port: 1003

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/Vellarasan/config-server